CREATE PROCEDURE [WebApi].[UpdateCustomerFromJson](@Customer NVARCHAR(MAX), @CustomerID int, @UserID int)
WITH EXECUTE AS OWNER
AS BEGIN
	UPDATE Sales.Customers SET
		CustomerName = ISNULL(json.CustomerName, Sales.Customers.CustomerName),
		BillToCustomerID = ISNULL(json.BillToCustomerID, Sales.Customers.BillToCustomerID),
		CustomerCategoryID = ISNULL(json.CustomerCategoryID, Sales.Customers.CustomerCategoryID),
		BuyingGroupID = json.BuyingGroupID,
		PrimaryContactPersonID = ISNULL(json.PrimaryContactPersonID, Sales.Customers.PrimaryContactPersonID),
		AlternateContactPersonID = ISNULL(json.AlternateContactPersonID, Sales.Customers.AlternateContactPersonID),
		DeliveryMethodID = ISNULL(json.DeliveryMethodID, Sales.Customers.DeliveryMethodID),
		DeliveryCityID = ISNULL(json.DeliveryCityID, Sales.Customers.DeliveryCityID),
		PostalCityID = ISNULL(json.PostalCityID, Sales.Customers.PostalCityID),
		CreditLimit = json.CreditLimit,
		AccountOpenedDate = ISNULL(json.AccountOpenedDate, Sales.Customers.AccountOpenedDate),
		StandardDiscountPercentage = ISNULL(json.StandardDiscountPercentage, Sales.Customers.StandardDiscountPercentage),
		IsStatementSent = ISNULL(json.IsStatementSent, Sales.Customers.IsStatementSent),
		IsOnCreditHold = ISNULL(json.IsOnCreditHold, Sales.Customers.IsOnCreditHold),
		PaymentDays = ISNULL(json.PaymentDays, Sales.Customers.PaymentDays),
		PhoneNumber = ISNULL(json.PhoneNumber, Sales.Customers.PhoneNumber),
		FaxNumber = ISNULL(json.FaxNumber, Sales.Customers.FaxNumber),
		DeliveryRun = json.DeliveryRun,
		RunPosition = json.RunPosition,
		WebsiteURL = ISNULL(json.WebsiteURL, Sales.Customers.WebsiteURL),
		DeliveryAddressLine1 = ISNULL(json.DeliveryAddressLine1, Sales.Customers.DeliveryAddressLine1),
		DeliveryAddressLine2 = json.DeliveryAddressLine2,
		DeliveryPostalCode = ISNULL(json.DeliveryPostalCode, Sales.Customers.DeliveryPostalCode),
		PostalAddressLine1 = ISNULL(json.PostalAddressLine1, Sales.Customers.PostalAddressLine1),
		PostalAddressLine2 = json.PostalAddressLine2,
		PostalPostalCode = ISNULL(json.PostalPostalCode, Sales.Customers.PostalPostalCode),
		LastEditedBy = @UserID
	FROM OPENJSON(@Customer)
		WITH (
			CustomerName nvarchar(100),
			BillToCustomerID int,
			CustomerCategoryID int,
			BuyingGroupID int,
			PrimaryContactPersonID int,
			AlternateContactPersonID int,
			DeliveryMethodID int,
			DeliveryCityID int,
			PostalCityID int,
			CreditLimit decimal(18,2),
			AccountOpenedDate date,
			StandardDiscountPercentage decimal(18,3),
			IsStatementSent bit,
			IsOnCreditHold bit,
			PaymentDays int,
			PhoneNumber nvarchar(20),
			FaxNumber nvarchar(20),
			DeliveryRun nvarchar(5),
			RunPosition nvarchar(5),
			WebsiteURL nvarchar(256),
			DeliveryAddressLine1 nvarchar(60),
			DeliveryAddressLine2 nvarchar(60),
			DeliveryPostalCode nvarchar(10),
			PostalAddressLine1 nvarchar(60),
			PostalAddressLine2 nvarchar(60),
			PostalPostalCode nvarchar(10)) as json
	WHERE 
		Sales.Customers.CustomerID = @CustomerID
END